"""Generate paper tables and figures from real CIFAR10/AWGN/C=32 CSV results."""

from __future__ import annotations

import csv
import math
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
LATEX_DIR = ROOT / "latex"
FIG_DIR = LATEX_DIR / "figures"
DATA_DIR = ROOT / "mismatch_results"

SNRS = [1, 4, 7, 10, 13]

METHODS = [
    ("Original", "Original", "original_cifar10_awgn_C32_msssim_cpu.csv"),
    ("UA", "UA-Delta3", "ua_delta3_cifar10_awgn_C32_msssim_cpu.csv"),
    ("Tail", "Tail-UA", "tail_ua_delta3_cifar10_awgn_C32_msssim_cpu.csv"),
    ("Cons", "Cons-UA", "cons_ua_delta3_cifar10_awgn_C32_msssim_cpu.csv"),
    ("TailCons", "Tail+Cons-UA", "tail_cons_ua_delta3_cifar10_awgn_C32_msssim_cpu.csv"),
]

COLORS = {
    "Original": "#4E79A7",
    "UA-Delta3": "#E15759",
    "Tail-UA": "#59A14F",
    "Cons-UA": "#F28E2B",
    "Tail+Cons-UA": "#B07AA1",
}


def load_results() -> dict[str, pd.DataFrame]:
    results = {}
    for key, _, filename in METHODS:
        path = DATA_DIR / filename
        if not path.exists():
            raise FileNotFoundError(f"Missing required result CSV: {path}")
        df = pd.read_csv(path)
        required = {"SNR_true", "SNR_hat", "PSNR", "MS_SSIM", "MS_SSIM_dB"}
        missing = required.difference(df.columns)
        if missing:
            raise ValueError(f"{path} is missing columns: {sorted(missing)}")
        if len(df) != 25:
            raise ValueError(f"{path} should contain a 5x5 mismatch matrix, got {len(df)} rows")
        results[key] = df
    return results


def matrix(df: pd.DataFrame, metric: str) -> np.ndarray:
    pivot = df.pivot(index="SNR_true", columns="SNR_hat", values=metric)
    return pivot.loc[SNRS, SNRS].to_numpy()


def summarize(df: pd.DataFrame) -> dict[str, float]:
    diag = df["SNR_true"].eq(df["SNR_hat"])
    off = ~diag
    return {
        "diag_psnr": df.loc[diag, "PSNR"].mean(),
        "off_psnr": df.loc[off, "PSNR"].mean(),
        "worst_psnr": df["PSNR"].min(),
        "diag_msd": df.loc[diag, "MS_SSIM_dB"].mean(),
        "off_msd": df.loc[off, "MS_SSIM_dB"].mean(),
        "worst_msd": df["MS_SSIM_dB"].min(),
    }


def fmt(value: float) -> str:
    return f"{value:.4f}"


def bold_if(value: float, best: float) -> str:
    text = fmt(value)
    if math.isclose(value, best, rel_tol=0.0, abs_tol=5e-5):
        return f"\\textbf{{{text}}}"
    return text


def write_tables(results: dict[str, pd.DataFrame]) -> dict[str, dict[str, float]]:
    summaries = {key: summarize(df) for key, df in results.items()}
    original = summaries["Original"]
    best = {
        metric: max(vals[metric] for vals in summaries.values())
        for metric in ["diag_psnr", "off_psnr", "worst_psnr", "diag_msd", "off_msd", "worst_msd"]
    }

    aggregate_rows = ["% Auto-generated by latex/generate_figures.py"]
    gain_rows = ["% Auto-generated by latex/generate_figures.py"]

    for key, label, _ in METHODS:
        vals = summaries[key]
        aggregate_rows.append(
            " & ".join(
                [
                    label,
                    bold_if(vals["diag_psnr"], best["diag_psnr"]),
                    bold_if(vals["off_psnr"], best["off_psnr"]),
                    bold_if(vals["worst_psnr"], best["worst_psnr"]),
                    bold_if(vals["diag_msd"], best["diag_msd"]),
                    bold_if(vals["off_msd"], best["off_msd"]),
                    bold_if(vals["worst_msd"], best["worst_msd"]),
                ]
            )
            + r" \\"
        )
        if key != "Original":
            gain_rows.append(
                " & ".join(
                    [
                        label,
                        f"{vals['off_psnr'] - original['off_psnr']:+.4f}",
                        f"{vals['worst_psnr'] - original['worst_psnr']:+.4f}",
                        f"{vals['off_msd'] - original['off_msd']:+.4f}",
                        f"{vals['worst_msd'] - original['worst_msd']:+.4f}",
                    ]
                )
                + r" \\"
            )

    (LATEX_DIR / "table_aggregate_rows.tex").write_text("\n".join(aggregate_rows) + "\n", encoding="utf-8")
    (LATEX_DIR / "table_gain_rows.tex").write_text("\n".join(gain_rows) + "\n", encoding="utf-8")

    ua = summaries["UA"]
    tail_cons = summaries["TailCons"]
    metrics = [
        "% Auto-generated by latex/generate_figures.py",
        f"\\newcommand{{\\OrigOffPSNR}}{{{original['off_psnr']:.4f}}}",
        f"\\newcommand{{\\UAOffPSNR}}{{{ua['off_psnr']:.4f}}}",
        f"\\newcommand{{\\GainOffPSNR}}{{{ua['off_psnr'] - original['off_psnr']:.4f}}}",
        f"\\newcommand{{\\OrigDiagPSNR}}{{{original['diag_psnr']:.4f}}}",
        f"\\newcommand{{\\UADiagPSNR}}{{{ua['diag_psnr']:.4f}}}",
        f"\\newcommand{{\\GainDiagPSNR}}{{{ua['diag_psnr'] - original['diag_psnr']:.4f}}}",
        f"\\newcommand{{\\OrigOffMSSSIMdB}}{{{original['off_msd']:.4f}}}",
        f"\\newcommand{{\\UAOffMSSSIMdB}}{{{ua['off_msd']:.4f}}}",
        f"\\newcommand{{\\GainOffMSSSIM}}{{{ua['off_msd'] - original['off_msd']:.4f}}}",
        f"\\newcommand{{\\GainDiagMSSSIM}}{{{ua['diag_msd'] - original['diag_msd']:.4f}}}",
        f"\\newcommand{{\\TailConsWorstPSNRGain}}{{{tail_cons['worst_psnr'] - original['worst_psnr']:.4f}}}",
        f"\\newcommand{{\\TailConsWorstMSSSIMGain}}{{{tail_cons['worst_msd'] - original['worst_msd']:.4f}}}",
        "",
    ]
    (LATEX_DIR / "generated_metrics.tex").write_text("\n".join(metrics), encoding="utf-8")
    return summaries


def write_case_table(results: dict[str, pd.DataFrame]) -> None:
    orig = results["Original"]
    ua = results["UA"]
    merged = orig.merge(ua, on=["SNR_true", "SNR_hat", "SNR_error", "C"], suffixes=("_orig", "_ua"))
    merged = merged[merged["SNR_true"] != merged["SNR_hat"]].copy()
    merged["gain"] = merged["PSNR_ua"] - merged["PSNR_orig"]
    merged = merged.sort_values("gain", ascending=False).head(5)
    rows = ["% Auto-generated by latex/generate_figures.py"]
    for row in merged.itertuples(index=False):
        rows.append(
            f"{int(row.SNR_true)} & {int(row.SNR_hat)} & "
            f"{row.PSNR_orig:.4f} & {row.PSNR_ua:.4f} & +{row.gain:.4f} \\\\"
        )
    (LATEX_DIR / "representative_cases_rows.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")


def save_all_formats(fig: plt.Figure, stem: str) -> None:
    for ext in ["pdf", "png", "svg"]:
        fig.savefig(FIG_DIR / f"{stem}.{ext}", bbox_inches="tight", dpi=450)


def setup_axes(ax: plt.Axes) -> None:
    ax.set_xticks(np.arange(len(SNRS)))
    ax.set_xticklabels(SNRS)
    ax.set_yticks(np.arange(len(SNRS)))
    ax.set_yticklabels(SNRS)
    ax.set_xlabel(r"Estimated SNR $\hat{\gamma}$ (dB)")
    ax.set_ylabel(r"True SNR $\gamma$ (dB)")


def annotate_heatmap(ax: plt.Axes, values: np.ndarray, color_threshold: float) -> None:
    for i in range(values.shape[0]):
        for j in range(values.shape[1]):
            color = "white" if values[i, j] < color_threshold else "black"
            ax.text(j, i, f"{values[i, j]:.1f}", ha="center", va="center", fontsize=6.5, color=color)


def plot_heatmaps(results: dict[str, pd.DataFrame], metric: str, stem: str, colorbar_label: str) -> None:
    orig = matrix(results["Original"], metric)
    ua = matrix(results["UA"], metric)
    gain = ua - orig

    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.35), constrained_layout=True)
    vmin = min(orig.min(), ua.min())
    vmax = max(orig.max(), ua.max())
    threshold = vmin + 0.45 * (vmax - vmin)

    for ax, data, title in [
        (axes[0], orig, "Original"),
        (axes[1], ua, "UA-Delta3"),
    ]:
        im = ax.imshow(data, cmap="viridis", vmin=vmin, vmax=vmax)
        ax.set_title(title, fontsize=9)
        setup_axes(ax)
        annotate_heatmap(ax, data, threshold)
    fig.colorbar(im, ax=axes[:2], shrink=0.82, pad=0.015, label=colorbar_label)

    gmax = max(abs(gain.min()), abs(gain.max()))
    im_gain = axes[2].imshow(gain, cmap="RdBu_r", vmin=-gmax, vmax=gmax)
    axes[2].set_title("UA - Original", fontsize=9)
    setup_axes(axes[2])
    for i in range(gain.shape[0]):
        for j in range(gain.shape[1]):
            axes[2].text(j, i, f"{gain[i, j]:+.1f}", ha="center", va="center", fontsize=6.5, color="black")
    fig.colorbar(im_gain, ax=axes[2], shrink=0.82, pad=0.015, label="Gain (dB)")
    save_all_formats(fig, stem)
    plt.close(fig)


def plot_aggregate(summaries: dict[str, dict[str, float]]) -> None:
    labels = [label for _, label, _ in METHODS]
    x = np.arange(len(labels))
    width = 0.34

    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.6), constrained_layout=True)
    for ax, off_key, worst_key, title, ylabel in [
        (axes[0], "off_psnr", "worst_psnr", "PSNR robustness", "PSNR (dB)"),
        (axes[1], "off_msd", "worst_msd", "MS-SSIM(dB) robustness", "MS-SSIM(dB)"),
    ]:
        off_vals = [summaries[key][off_key] for key, _, _ in METHODS]
        worst_vals = [summaries[key][worst_key] for key, _, _ in METHODS]
        ax.bar(x - width / 2, off_vals, width, label="Off-diagonal avg.", color="#4E79A7")
        ax.bar(x + width / 2, worst_vals, width, label="Worst case", color="#E15759")
        ax.set_title(title, fontsize=9)
        ax.set_ylabel(ylabel)
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=25, ha="right", fontsize=7)
        ax.grid(axis="y", linestyle=":", linewidth=0.5, alpha=0.7)
        ax.legend(fontsize=7, frameon=False)
    save_all_formats(fig, "fig3_aggregate_bars")
    plt.close(fig)


def write_figure_wrappers() -> None:
    wrappers = {
        "fig2_psnr_heatmaps.tex": (
            "figure*",
            "fig2_psnr_heatmaps.pdf",
            "PSNR mismatch heatmaps on CIFAR10/AWGN/C=32. Rows denote the true physical SNR $\\gamma$, columns denote the estimated modulation SNR $\\hat{\\gamma}$, and entries are in dB. The right panel reports the cell-wise UA-Delta3 gain over the original SwinJSCC checkpoint.",
            "fig:psnr-heatmaps",
            "\\textwidth",
        ),
        "fig3_aggregate_bars.tex": (
            "figure*",
            "fig3_aggregate_bars.pdf",
            "Aggregate robustness comparison across the original checkpoint and imperfect-CSI training variants. Off-diagonal averages characterize average mismatch robustness, while worst-case values characterize the weakest SNR pair in the matrix.",
            "fig:aggregate-bars",
            "\\textwidth",
        ),
        "fig4_msssim_heatmaps.tex": (
            "figure*",
            "fig4_msssim_heatmaps.pdf",
            "MS-SSIM(dB) mismatch heatmaps on CIFAR10/AWGN/C=32. The pattern is consistent with PSNR: UA-Delta3 improves most off-diagonal regions while slightly reducing the matched-SNR diagonal average.",
            "fig:msssim-heatmaps",
            "\\textwidth",
        ),
    }
    for filename, (env, image, caption, label, width) in wrappers.items():
        text = "\n".join(
            [
                "% Auto-generated by latex/generate_figures.py",
                f"\\begin{{{env}}}[t]",
                "\\centering",
                f"\\includegraphics[width={width}]{{figures/{Path(image).stem}}}",
                f"\\caption{{{caption}}}",
                f"\\label{{{label}}}",
                f"\\end{{{env}}}",
                "",
            ]
        )
        (FIG_DIR / filename).write_text(text, encoding="utf-8")


def main() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    results = load_results()
    summaries = write_tables(results)
    write_case_table(results)
    plot_heatmaps(results, "PSNR", "fig2_psnr_heatmaps", "PSNR (dB)")
    plot_aggregate(summaries)
    plot_heatmaps(results, "MS_SSIM_dB", "fig4_msssim_heatmaps", "MS-SSIM(dB)")
    write_figure_wrappers()
    print(f"Generated paper assets in {FIG_DIR}")


if __name__ == "__main__":
    main()
