"""Generate TikZ/LaTeX data figures from real mismatch CSV files.

The script intentionally uses only the Python standard library so it can run
without installing plotting dependencies. Outputs are native TikZ fragments
included by latex/main.tex.
"""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LATEX_DIR = ROOT / "latex"
FIG_DIR = LATEX_DIR / "figures"
DATA_DIR = ROOT / "mismatch_results"

ORIG_CSV = DATA_DIR / "original_cifar10_awgn_C32_msssim_cpu.csv"
UA_CSV = DATA_DIR / "ua_delta3_cifar10_awgn_C32_msssim_cpu.csv"

SNRS = [1, 4, 7, 10, 13]


def read_matrix(path: Path, metric: str) -> dict[tuple[int, int], float]:
    matrix: dict[tuple[int, int], float] = {}
    with path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            key = (int(row["SNR_true"]), int(row["SNR_hat"]))
            matrix[key] = float(row[metric])
    return matrix


def lerp(a: int, b: int, t: float) -> int:
    return int(round(a + (b - a) * max(0.0, min(1.0, t))))


def sequential_color(value: float, vmin: float, vmax: float) -> tuple[int, int, int]:
    """Colorblind-friendly blue-to-yellow ramp."""
    t = 0.5 if vmax == vmin else (value - vmin) / (vmax - vmin)
    stops = [
        (35, 55, 95),
        (46, 134, 171),
        (104, 190, 161),
        (246, 211, 101),
    ]
    pos = t * (len(stops) - 1)
    idx = min(int(pos), len(stops) - 2)
    frac = pos - idx
    c0, c1 = stops[idx], stops[idx + 1]
    return tuple(lerp(c0[i], c1[i], frac) for i in range(3))


def diverging_color(value: float, max_abs: float) -> tuple[int, int, int]:
    """Blue-white-red ramp centered at zero."""
    if max_abs <= 0:
        return (245, 245, 245)
    t = max(-1.0, min(1.0, value / max_abs))
    if t < 0:
        c0, c1, frac = (49, 104, 142), (245, 245, 245), t + 1.0
    else:
        c0, c1, frac = (245, 245, 245), (190, 55, 65), t
    return tuple(lerp(c0[i], c1[i], frac) for i in range(3))


def luminance(rgb: tuple[int, int, int]) -> float:
    r, g, b = rgb
    return 0.299 * r + 0.587 * g + 0.114 * b


def rgb_spec(rgb: tuple[int, int, int]) -> str:
    r, g, b = rgb
    return f"{{rgb,255:red,{r};green,{g};blue,{b}}}"


def panel_heatmap(
    name: str,
    matrix: dict[tuple[int, int], float],
    xshift: float,
    vmin: float,
    vmax: float,
    mode: str,
) -> list[str]:
    lines = [f"\\begin{{scope}}[xshift={xshift:.2f}cm]"]
    lines.append(f"\\node[font=\\bfseries\\scriptsize] at (2.25,4.95) {{{name}}};")
    cell = 0.82
    for row, true_snr in enumerate(reversed(SNRS)):
        y = (len(SNRS) - 1 - row) * cell
        lines.append(f"\\node[anchor=east,font=\\scriptsize] at (-0.08,{y + cell / 2:.2f}) {{{true_snr}}};")
        for col, hat_snr in enumerate(SNRS):
            x = col * cell
            val = matrix[(true_snr, hat_snr)]
            color = diverging_color(val, max(abs(vmin), abs(vmax))) if mode == "diverging" else sequential_color(val, vmin, vmax)
            text_color = "white" if luminance(color) < 110 else "black"
            lines.append(
                "\\filldraw[draw=white,line width=0.25pt,"
                f"fill={rgb_spec(color)}] ({x:.2f},{y:.2f}) rectangle "
                f"({x + cell:.2f},{y + cell:.2f});"
            )
            lines.append(
                f"\\node[font=\\tiny,text={text_color}] at "
                f"({x + cell / 2:.2f},{y + cell / 2:.2f}) {{{val:.1f}}};"
            )
    for col, hat_snr in enumerate(SNRS):
        x = col * cell
        lines.append(f"\\node[font=\\scriptsize] at ({x + cell / 2:.2f},-0.25) {{{hat_snr}}};")
    lines.append("\\node[font=\\scriptsize] at (2.05,-0.62) {$\\hat{\\gamma}$ (dB)};")
    lines.append("\\node[rotate=90,font=\\scriptsize] at (-0.72,2.05) {$\\gamma$ (dB)};")
    lines.append("\\end{scope}")
    return lines


def generate_heatmaps(orig: dict[tuple[int, int], float], ua: dict[tuple[int, int], float]) -> None:
    gain = {k: ua[k] - orig[k] for k in orig}
    all_abs = list(orig.values()) + list(ua.values())
    vmin, vmax = min(all_abs), max(all_abs)
    gmax = max(abs(v) for v in gain.values())

    body = [
        "% Auto-generated by latex/generate_figures.py",
        "\\begin{figure*}[t]",
        "\\centering",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tikzpicture}[x=1cm,y=1cm]",
    ]
    body += panel_heatmap("Original PSNR", orig, 0.0, vmin, vmax, "sequential")
    body += panel_heatmap("UA PSNR", ua, 5.05, vmin, vmax, "sequential")
    body += panel_heatmap("UA $-$ Original", gain, 10.10, -gmax, gmax, "diverging")
    body += [
        "\\end{tikzpicture}%",
        "}",
        "\\caption{PSNR mismatch heatmaps on CIFAR10/AWGN/C=32. Rows denote the true physical SNR $\\gamma$, columns denote the estimated modulation SNR $\\hat{\\gamma}$, and all entries are in dB. The right panel reports the cell-wise gain of uncertainty-aware training over the original SwinJSCC checkpoint.}",
        "\\label{fig:mismatch-heatmaps}",
        "\\end{figure*}",
        "",
    ]
    (FIG_DIR / "fig2_mismatch_heatmaps.tex").write_text("\n".join(body), encoding="utf-8")


def averages(matrix: dict[tuple[int, int], float]) -> tuple[float, float]:
    diag = [matrix[(s, s)] for s in SNRS]
    off = [v for (t, h), v in matrix.items() if t != h]
    return sum(diag) / len(diag), sum(off) / len(off)


def generate_tradeoff(orig_psnr: dict[tuple[int, int], float], ua_psnr: dict[tuple[int, int], float], orig_ms: dict[tuple[int, int], float], ua_ms: dict[tuple[int, int], float]) -> None:
    orig_diag, orig_off = averages(orig_psnr)
    ua_diag, ua_off = averages(ua_psnr)
    orig_ms_diag, orig_ms_off = averages(orig_ms)
    ua_ms_diag, ua_ms_off = averages(ua_ms)

    metrics_tex = "\n".join(
        [
            "% Auto-generated by latex/generate_figures.py",
            f"\\newcommand{{\\OrigOffPSNR}}{{{orig_off:.4f}}}",
            f"\\newcommand{{\\UAOffPSNR}}{{{ua_off:.4f}}}",
            f"\\newcommand{{\\GainOffPSNR}}{{{ua_off - orig_off:.4f}}}",
            f"\\newcommand{{\\OrigDiagPSNR}}{{{orig_diag:.4f}}}",
            f"\\newcommand{{\\UADiagPSNR}}{{{ua_diag:.4f}}}",
            f"\\newcommand{{\\GainDiagPSNR}}{{{ua_diag - orig_diag:.4f}}}",
            f"\\newcommand{{\\GainOffMSSSIM}}{{{ua_ms_off - orig_ms_off:.4f}}}",
            f"\\newcommand{{\\GainDiagMSSSIM}}{{{ua_ms_diag - orig_ms_diag:.4f}}}",
            "",
        ]
    )
    (LATEX_DIR / "generated_metrics.tex").write_text(metrics_tex, encoding="utf-8")

    body = [
        "% Auto-generated by latex/generate_figures.py",
        "\\begin{figure}[t]",
        "\\centering",
        "\\resizebox{\\columnwidth}{!}{%",
        "\\begin{tikzpicture}[font=\\scriptsize,x=1cm,y=1cm]",
        "\\draw[->] (0,0) -- (5.8,0);",
        "\\draw[->] (0,0) -- (0,4.2);",
        "\\node[rotate=90] at (-0.55,2.1) {Average PSNR (dB)};",
        "\\foreach \\y/\\lab in {0/0,1/10,2/20,3/30,4/40}{\\draw (-0.04,\\y) -- (0.04,\\y); \\node[anchor=east] at (-0.08,\\y) {\\lab};}",
    ]
    bars = [
        (0.8, orig_off, "Original", (49, 104, 142)),
        (1.35, ua_off, "UA", (190, 55, 65)),
        (3.2, orig_diag, "Original", (49, 104, 142)),
        (3.75, ua_diag, "UA", (190, 55, 65)),
    ]
    for x, val, label, color in bars:
        h = val / 10.0
        body.append(f"\\fill[{rgb_spec(color)}] ({x:.2f},0) rectangle ({x + 0.42:.2f},{h:.3f});")
        body.append(f"\\node[rotate=90,anchor=west] at ({x + 0.21:.2f},{h + 0.06:.3f}) {{{val:.1f}}};")
        body.append(f"\\node[rotate=35,anchor=east] at ({x + 0.34:.2f},-0.15) {{{label}}};")
    body += [
        "\\node[font=\\bfseries] at (1.28,-0.72) {Off-diagonal};",
        "\\node[font=\\bfseries] at (3.68,-0.72) {Diagonal};",
        f"\\node[align=center] at (5.05,3.55) {{+{ua_off - orig_off:.2f} dB\\\\off-diagonal}};",
        f"\\node[align=center] at (5.05,2.75) {{{ua_diag - orig_diag:.2f} dB\\\\diagonal}};",
        "\\end{tikzpicture}%",
        "}",
        "\\caption{Aggregate PSNR trade-off. UA improves the off-diagonal mismatch average while nearly preserving the matched-SNR diagonal average.}",
        "\\label{fig:aggregate-tradeoff}",
        "\\end{figure}",
        "",
    ]
    (FIG_DIR / "fig3_aggregate_tradeoff.tex").write_text("\n".join(body), encoding="utf-8")


def generate_case_gains(orig: dict[tuple[int, int], float], ua: dict[tuple[int, int], float]) -> None:
    cases = sorted(((ua[k] - orig[k], k, orig[k], ua[k]) for k in orig if k[0] != k[1]), reverse=True)[:5]
    max_gain = max(g for g, _, _, _ in cases)
    body = [
        "% Auto-generated by latex/generate_figures.py",
        "\\begin{figure}[t]",
        "\\centering",
        "\\resizebox{\\columnwidth}{!}{%",
        "\\begin{tikzpicture}[font=\\scriptsize,x=1cm,y=1cm]",
        "\\draw[->] (0,0) -- (5.3,0);",
        "\\draw[->] (0,0) -- (0,3.7);",
        "\\node at (2.65,-0.48) {PSNR gain (dB)};",
    ]
    for i, (gain, (true_snr, hat_snr), orig_val, ua_val) in enumerate(cases):
        y = 3.2 - i * 0.62
        width = 4.35 * gain / max_gain
        body.append(f"\\fill[{rgb_spec((190, 55, 65))}] (0,{y - 0.18:.2f}) rectangle ({width:.2f},{y + 0.18:.2f});")
        body.append(f"\\node[anchor=east] at (-0.08,{y:.2f}) {{$({true_snr},{hat_snr})$}};")
        body.append(f"\\node[anchor=west] at ({width + 0.08:.2f},{y:.2f}) {{+{gain:.2f}}};")
    body += [
        "\\node[rotate=90] at (-1.02,1.75) {$(\\gamma,\\hat{\\gamma})$ in dB};",
        "\\end{tikzpicture}%",
        "}",
        "\\caption{Representative off-diagonal PSNR gains. The largest gain occurs when a poor physical channel is overestimated, i.e., $\\gamma=1$ dB and $\\hat{\\gamma}=7$ dB.}",
        "\\label{fig:case-gains}",
        "\\end{figure}",
        "",
    ]
    (FIG_DIR / "fig4_representative_gains.tex").write_text("\n".join(body), encoding="utf-8")

    table_lines = [
        "% Auto-generated by latex/generate_figures.py",
    ]
    for gain, (true_snr, hat_snr), orig_val, ua_val in cases:
        table_lines.append(f"{true_snr} & {hat_snr} & {orig_val:.4f} & {ua_val:.4f} & +{gain:.4f} \\\\")
    (LATEX_DIR / "representative_cases_rows.tex").write_text("\n".join(table_lines) + "\n", encoding="utf-8")


def main() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    orig_psnr = read_matrix(ORIG_CSV, "PSNR")
    ua_psnr = read_matrix(UA_CSV, "PSNR")
    orig_ms = read_matrix(ORIG_CSV, "MS_SSIM")
    ua_ms = read_matrix(UA_CSV, "MS_SSIM")
    generate_heatmaps(orig_psnr, ua_psnr)
    generate_tradeoff(orig_psnr, ua_psnr, orig_ms, ua_ms)
    generate_case_gains(orig_psnr, ua_psnr)
    print(f"Generated LaTeX figures in {FIG_DIR}")


if __name__ == "__main__":
    main()
