"""Generate CL paper tables and figures from real mismatch CSV results."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
LATEX_DIR = ROOT / "latex"
FIG_DIR = LATEX_DIR / "figures"
DATA_DIR = ROOT / "mismatch_results"
SNRS = [1, 4, 7, 10, 13]

plt.rcParams["svg.fonttype"] = "none"
plt.rcParams["font.family"] = "DejaVu Sans"

PRIMARY_RESULTS = [
    ("Original", "Original", "original_cifar10_awgn_C32_msssim_cpu.csv", True),
    ("D0", "Perfect-CSI FT (D0)", "ua-d0-eval_CIFAR10_awgn_SwinJSCC_w-SA_C32_ckpt-*_EP10_msssim_cpu.csv", False),
    ("D1", "UA-D1", "ua-d1-eval_CIFAR10_awgn_SwinJSCC_w-SA_C32_ckpt-*_EP10_msssim_cpu.csv", True),
    ("D3", "UA-D3", "ua_delta3_cifar10_awgn_C32_msssim_cpu.csv", True),
    ("D6", "UA-D6", "ua-d6-eval_CIFAR10_awgn_SwinJSCC_w-SA_C32_ckpt-*_EP10_msssim_cpu.csv", True),
    ("RandomHat", "Random-hat", "random-hat-eval_CIFAR10_awgn_SwinJSCC_w-SA_C32_ckpt-*_EP10_msssim_cpu.csv", True),
]

RAYLEIGH_RESULTS = [
    ("RayOrig", "Original", "rayleigh-original-eval_CIFAR10_rayleigh_SwinJSCC_w-SA_C32_ckpt-*_msssim_cpu.csv"),
    ("RayUA", "UA-D3", "rayleigh-ua-d3-eval_CIFAR10_rayleigh_SwinJSCC_w-SA_C32_ckpt-*_EP10_msssim_cpu.csv"),
]


def resolve_csv(pattern: str, required: bool) -> Path | None:
    exact = DATA_DIR / pattern
    if exact.exists():
        return exact
    matches = sorted(DATA_DIR.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    if matches:
        return matches[0]
    if required:
        raise FileNotFoundError(f"Missing required result CSV matching {pattern!r} in {DATA_DIR}")
    print(f"WARNING: missing optional result CSV matching {pattern!r}; emitting TODO row.")
    return None


def read_result(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    required = {"SNR_true", "SNR_hat", "PSNR", "MS_SSIM", "MS_SSIM_dB"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"{path} is missing columns: {sorted(missing)}")
    if len(df) != 25:
        raise ValueError(f"{path} should contain a 5x5 mismatch matrix, got {len(df)} rows")
    return df


def summarize(df: pd.DataFrame) -> dict[str, float]:
    diag = df["SNR_true"].eq(df["SNR_hat"])
    off = ~diag
    return {
        "diag_psnr": df.loc[diag, "PSNR"].mean(),
        "off_psnr": df.loc[off, "PSNR"].mean(),
        "worst_psnr": df["PSNR"].min(),
        "diag_msd": df.loc[diag, "MS_SSIM_dB"].mean(),
        "off_msd": df.loc[off, "MS_SSIM_dB"].mean(),
        "worst_msd": df["MS_SSIM_dB"].min(),
    }


def matrix(df: pd.DataFrame, metric: str) -> np.ndarray:
    pivot = df.pivot(index="SNR_true", columns="SNR_hat", values=metric)
    return pivot.loc[SNRS, SNRS].to_numpy()


def load_primary() -> tuple[dict[str, pd.DataFrame], dict[str, str], set[str]]:
    data: dict[str, pd.DataFrame] = {}
    labels: dict[str, str] = {}
    missing: set[str] = set()
    for key, label, pattern, required in PRIMARY_RESULTS:
        labels[key] = label
        path = resolve_csv(pattern, required)
        if path is None:
            missing.add(key)
            continue
        data[key] = read_result(path)
    return data, labels, missing


def load_rayleigh() -> tuple[dict[str, pd.DataFrame], dict[str, str]]:
    data: dict[str, pd.DataFrame] = {}
    labels: dict[str, str] = {}
    for key, label, pattern in RAYLEIGH_RESULTS:
        labels[key] = label
        path = resolve_csv(pattern, required=False)
        if path is not None:
            data[key] = read_result(path)
    return data, labels


def fmt(value: float) -> str:
    return f"{value:.2f}"


def gain(value: float, reference: float) -> str:
    return f"{value - reference:+.2f}"


def write_tradeoff_table(data: dict[str, pd.DataFrame], labels: dict[str, str], missing: set[str]) -> dict[str, dict[str, float]]:
    summaries = {key: summarize(df) for key, df in data.items()}
    original = summaries["Original"]
    rows = ["% Auto-generated by latex/generate_figures.py"]

    for key, label, _, _ in PRIMARY_RESULTS:
        if key in missing:
            rows.append(f"{label} & \\multicolumn{{6}}{{c}}{{TODO: D0-EP10 CPU result missing}} \\\\")
            continue
        vals = summaries[key]
        rows.append(
            " & ".join(
                [
                    labels[key],
                    fmt(vals["diag_psnr"]),
                    fmt(vals["off_psnr"]),
                    fmt(vals["worst_psnr"]),
                    gain(vals["diag_psnr"], original["diag_psnr"]),
                    gain(vals["off_psnr"], original["off_psnr"]),
                    fmt(vals["off_msd"]),
                ]
            )
            + r" \\"
        )
    (LATEX_DIR / "table_tradeoff_rows.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")
    return summaries


def write_rayleigh_table(data: dict[str, pd.DataFrame], labels: dict[str, str]) -> dict[str, dict[str, float]]:
    rows = ["% Auto-generated by latex/generate_figures.py"]
    summaries = {key: summarize(df) for key, df in data.items()}
    if {"RayOrig", "RayUA"}.issubset(summaries):
        orig = summaries["RayOrig"]
        for key in ["RayOrig", "RayUA"]:
            vals = summaries[key]
            rows.append(
                " & ".join(
                    [
                        labels[key],
                        fmt(vals["diag_psnr"]),
                        fmt(vals["off_psnr"]),
                        fmt(vals["worst_psnr"]),
                        gain(vals["off_psnr"], orig["off_psnr"]),
                        fmt(vals["off_msd"]),
                    ]
                )
                + r" \\"
            )
    else:
        rows.append("\\multicolumn{6}{c}{Rayleigh CPU results unavailable} \\\\")
    (LATEX_DIR / "table_rayleigh_rows.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")
    return summaries


def write_metrics(primary: dict[str, dict[str, float]], rayleigh: dict[str, dict[str, float]]) -> None:
    orig = primary["Original"]
    d3 = primary["D3"]
    d6 = primary["D6"]
    rand = primary["RandomHat"]
    lines = [
        "% Auto-generated by latex/generate_figures.py",
        f"\\newcommand{{\\DThreeOffGain}}{{{d3['off_psnr'] - orig['off_psnr']:.2f}}}",
        f"\\newcommand{{\\DThreeDiagGain}}{{{d3['diag_psnr'] - orig['diag_psnr']:.2f}}}",
        f"\\newcommand{{\\DSixOffGain}}{{{d6['off_psnr'] - orig['off_psnr']:.2f}}}",
        f"\\newcommand{{\\DSixDiagGain}}{{{d6['diag_psnr'] - orig['diag_psnr']:.2f}}}",
        f"\\newcommand{{\\RandomOffGain}}{{{rand['off_psnr'] - orig['off_psnr']:.2f}}}",
        f"\\newcommand{{\\RandomDiagGain}}{{{rand['diag_psnr'] - orig['diag_psnr']:.2f}}}",
    ]
    if {"RayOrig", "RayUA"}.issubset(rayleigh):
        lines.append(f"\\newcommand{{\\RayleighOffGain}}{{{rayleigh['RayUA']['off_psnr'] - rayleigh['RayOrig']['off_psnr']:.2f}}}")
    else:
        lines.append("\\newcommand{\\RayleighOffGain}{TODO}")
    lines.append("")
    (LATEX_DIR / "generated_metrics.tex").write_text("\n".join(lines), encoding="utf-8")


def setup_heatmap_axes(ax: plt.Axes) -> None:
    ax.set_xticks(np.arange(len(SNRS)))
    ax.set_xticklabels(SNRS)
    ax.set_yticks(np.arange(len(SNRS)))
    ax.set_yticklabels(SNRS)
    ax.set_xlabel(r"Estimated SNR $\hat{\gamma}$ (dB)")
    ax.set_ylabel(r"True SNR $\gamma$ (dB)")


def annotate_values(ax: plt.Axes, values: np.ndarray, gain_mode: bool, threshold: float = 25.0) -> None:
    for i in range(values.shape[0]):
        for j in range(values.shape[1]):
            if gain_mode:
                label = f"{values[i, j]:+.1f}"
                if "." not in label:
                    raise ValueError(f"Gain label lost decimal point: {label}")
                color = "black"
            else:
                label = f"{values[i, j]:.1f}"
                color = "white" if values[i, j] < threshold else "black"
            ax.text(j, i, label, ha="center", va="center", fontsize=6.4, color=color)


def plot_psnr_heatmap(data: dict[str, pd.DataFrame]) -> None:
    orig = matrix(data["Original"], "PSNR")
    d3 = matrix(data["D3"], "PSNR")
    diff = d3 - orig
    if np.any(np.abs(diff) >= 10):
        raise ValueError("Unexpected gain magnitude >= 10 dB; check heatmap labels before export.")

    fig, axes = plt.subplots(1, 3, figsize=(7.15, 2.25), constrained_layout=True)
    vmin = min(orig.min(), d3.min())
    vmax = max(orig.max(), d3.max())
    text_threshold = vmin + 0.45 * (vmax - vmin)

    for ax, values, title in [(axes[0], orig, "Original"), (axes[1], d3, "UA-D3")]:
        im = ax.imshow(values, cmap="viridis", vmin=vmin, vmax=vmax)
        ax.set_title(title, fontsize=9)
        setup_heatmap_axes(ax)
        annotate_values(ax, values, gain_mode=False, threshold=text_threshold)
    fig.colorbar(im, ax=axes[:2], shrink=0.82, pad=0.015, label="PSNR (dB)")

    gmax = max(abs(diff.min()), abs(diff.max()))
    im_gain = axes[2].imshow(diff, cmap="RdBu_r", vmin=-gmax, vmax=gmax)
    axes[2].set_title("UA-D3 - Original", fontsize=9)
    setup_heatmap_axes(axes[2])
    annotate_values(axes[2], diff, gain_mode=True)
    fig.colorbar(im_gain, ax=axes[2], shrink=0.82, pad=0.015, label="Gain (dB)")

    for ext in ["pdf", "png", "svg"]:
        fig.savefig(FIG_DIR / f"fig2_psnr_heatmaps.{ext}", bbox_inches="tight", dpi=450)
    plt.close(fig)
    svg_path = FIG_DIR / "fig2_psnr_heatmaps.svg"
    svg_text = svg_path.read_text(encoding="utf-8")
    svg_path.write_text("\n".join(line.rstrip() for line in svg_text.splitlines()) + "\n", encoding="utf-8")

    wrapper = "\n".join(
        [
            "% Auto-generated by latex/generate_figures.py",
            "\\begin{figure*}[t]",
            "\\centering",
            "\\includegraphics[width=\\textwidth]{figures/fig2_psnr_heatmaps}",
            "\\caption{PSNR heatmaps under SNR mismatch on CIFAR10/AWGN/C=32. Rows denote the true physical SNR $\\gamma$, columns denote the estimated modulation SNR $\\hat{\\gamma}$, and the right panel reports the UA-D3 gain over the original checkpoint.}",
            "\\label{fig:psnr-heatmaps}",
            "\\end{figure*}",
            "",
        ]
    )
    (FIG_DIR / "fig2_psnr_heatmaps.tex").write_text(wrapper, encoding="utf-8")


def main() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    primary_data, primary_labels, missing = load_primary()
    rayleigh_data, rayleigh_labels = load_rayleigh()
    primary_summary = write_tradeoff_table(primary_data, primary_labels, missing)
    rayleigh_summary = write_rayleigh_table(rayleigh_data, rayleigh_labels)
    write_metrics(primary_summary, rayleigh_summary)
    plot_psnr_heatmap(primary_data)
    if "D0" in missing:
        print("TODO: D0-EP10 CPU CSV is missing. Do not use D0-EP5 as the formal perfect-CSI fine-tuning baseline.")
    print(f"Generated CL paper assets in {FIG_DIR}")


if __name__ == "__main__":
    main()
